version: '3.3'
services:
  web:
    image: ideaspositivas/odoo:12.0-stable
    restart: always
    depends_on:
      - db
    ports:
      - '8069'
      - '8072'
    volumes:
      - 'odoo-data:/var/lib/odoo'
      - './config:/etc/odoo/base'
      - './addons:/addons'
    environment:
      - PGUSER=odoo
      - PGPASSWORD=${password('postgres')}
      - PGHOST=db
      - PGDATABASE=postgres
      - ODOO_PRIORITY_ADDONS_PATH=/addons/ilex-odoo-2.1,/addons/ilex-2.1
    networks:
      - default
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 150m
  db:
    image: 'postgres:10'
    command: postgres -c 'max_connections=1000'
    restart: always
    ports:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=${password('postgres')}
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGPASS=${password('postgres')}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: 20m
volumes:
  postgres-data: null
  odoo-data: null
