version: '3.3'
services:
  web:
    image: ideaspositivas/odoo:15.0-stable
    restart: always
    depends_on:
      - db
    ports:
      - '8069'
      - '8072'
    volumes:
      - 'odoo-data:/var/lib/odoo'
      - './config:/etc/odoo/base'
      - './addons:/addons'
    environment:
      - PGUSER=odoo
      - PGPASSWORD=${password('postgres')}
      - PGHOST=db
      - PGDATABASE=postgres
      - ODOO_PRIORITY_ADDONS_PATH=/addons/ilex-odoo-3.0
    networks:
      - default
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 150m
  db:
    image: 'postgres:10'
    command: postgres  -c max_connections=1000 -c shared_buffers=1GB -c effective_cache_size=3GB -c maintenance_work_mem=256MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=524kB -c min_wal_size=1GB -c max_wal_size=4GB
    restart: always
    ports:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=${password('postgres')}
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGPASS=${password('postgres')}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: 20m
volumes:
  postgres-data: null
  odoo-data: null
